[package]
name = "fastcover"
version = "0.1.0"
edition = "2024"
default-run = "fastcover"
license = "MIT OR Apache-2.0"
description = "Long-read metagenomic redundancy, coverage, and diversity estimation"
repository = "https://github.com/jianshu93/fastcover"

[[bin]]
name = "fastcover"
path = "src/bin/fastcover.rs"

[[bin]]
name = "fastcover-plot"
path = "src/bin/fastcover-plot.rs"

[dependencies]
anyhow = "1.0"
clap = { version = "4.5", features = ["derive"] }
needletail = "0.6"
num_cpus = "1"
plotters = { version = "0.3.7", default-features = false, features = ["svg_backend", "line_series", "point_series", "full_palette"] }
rand = "0.8"
rand_chacha = "0.3"
rammap-core = { version = "1.1.2", default-features = false }
rayon = "1.10"
rustc-hash = "2.1"
simd-minimizers = "3.0.0"
svg2pdf = { version = "0.13", default-features = false, features = ["text"] }
tab-hash = "0.4.0"
wide = "=1.5.0"

[profile.release]
lto = "thin"
codegen-units = 1
